version: '3'

services:
  app:
  container_name: back
  env_file: ./back/.env
  ports:
      - 3001:3001
  build: 
  context: .
  dockerfile: ./back.dockerfile
  volumes:
      - ./back:/back
      - /back/node_modules
  networks:
      - chat-network
  tty: true
  command: ["npm", "run", "dev"]

  web:
    container_name: front
    env_file: ./front/.env
    ports:
    - 8080:8080
    build: 
      context: .
      dockerfile: ./front.dockerfile
    volumes:
      - next-app-build:/front
    networks:
      - chat-network
    depends_on:
      - app
    tty: true

  nginx:
    container_name: nginx   
    build: 
        context: ./.nginx
        dockerfile: nginx.dockerfile
    image: nginx
    volumes:
      - next-app-build:/front
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "81:80"
    networks:
      - chat-network
    depends_on:
      - app
      - web
    tty: true
networks:
  chat-network:
    driver: bridge

volumes:
  next-app-build:
