on:
        push:
                branches:
                        - main

jobs:
        deploy:
                runs-on: ubuntu-latest

                steps:
                        - name: Checkout Repository
                          uses: actions/checkout@v4

                        - name: Set up node
                          uses: actions/setup-node@v4
                          with:
                                  node-version: '20.15.0'
                        
                        - name: Set up Keys
                          uses: kielabokkie/ssh-key-and-known-hosts-action@v1
                          with:
                                  ssh-private-key: ${{ secrets.ORACLE_GITHUB_SSH_KEY }}
                                  ssh-host: ${{ secrets.ORACLE_REMOTE_SERVER_IP }}

                        - name: Deploy
                          run: make deploy
